osx_image: xcode8.3
dist: trusty
sudo: required

services:
- docker

language: node_js
node_js: '6'

os:
- linux
- osx

env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  
cache:
  directories:
  - "$HOME/.yarn-cache"
  
before_install:
  #disable code signing on branches different from master
- if [[ $TRAVIS_BRANCH != 'master' ]]; then CSC_LINK=""; fi
- if [[ $TRAVIS_BRANCH == 'master' ]]; then openssl aes-256-cbc -K $encrypted_33866e2c6dd4_key -iv $encrypted_33866e2c6dd4_iv -in build/certs/apple.p12.enc -out build/certs/apple.p12 -d ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y -qq yarn; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull electronuserland/electron-builder:wine; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --ignore-dependencies yarn; fi
install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn install; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -ti -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --env-file <(env | grep TRAVIS) -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules -v ~/.electron:/root/.electron electronuserland/electron-builder:6 /bin/bash -c "yarn && yarn dist:linux"; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn dist:mac; fi
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
notifications:
  email: false

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "fermiumlabs-software-builds"
  skip_cleanup: true
  local_dir: dist
  upload-dir: nng-logger/$TRAVIS_COMMIT/
