---
# File di configurazione

product:
  manufacturer: "ACME Inc."
  manufacturercode : "ACME"
  name: "Hall effect apparatus"
  model: "hall-123A-plus"
  description: ""
  picture: ""
manual:
  # URL should be HTTPS
  url: "https://example.com/manuals/hall-effect.pdf"
  #If a git repository is specified and available, the previous url will be ignored
  git:
    user: "fermiumlabs"
    repo: "hall-effect-handbook"
    tag: "latest"
    filename: "Hall_Handbook.pdf" #PDF is the only filetype supported
config:
  mathsheet: |
    vh1 = ch1 V
    vh2 = ch2 V
    vh = vh1-vh1*k+vh2*k
    temp = ch3 K
    vr = ch4 V
    I = ch5 A
    r = vr/(I/100)
    B = ch6 T
  channels:
      - name: "ch1"
        code: 1  #unique data-chan identifier
        gain: 1  #default gain
        gainvalues: [0.5, 1, 2, 5, 10, 20, 50, 100] #mapped to a 0-N array
        description: "Voltage output of the first channel"
  calibration:

  inputs :
      #- name: the name of the input
      #  type: type of the input field, supports all html5 types and slider (except dropdown for now)
      #  min: minimum value if exists
      #  max: maximum value if exists
      #  values: array of values for dropdown
      #  step: i think this is quite clear
      #  default: default value for the input
      #  hardware : boolean, if true the value must be sent to the device
      - name: "k"
        type: "slider"
        min: 0
        max: 1
        step: 0.001
        default: 0.7
      - name: "power"
        type: "slider"
        min: 0
        max: 1
        step: 0.001
        default: 0
        sendtohardware : true
