---
# File di configurazione
product:
  manufacturer: "LabTrek"
  manufacturercode : "labtrek"
  name: "Microware Bench"
  model: "ltk-mw"
  description: "Realize hundreds of experiments in a single intregrated microware bench (upcoming !)"
  image: "pic.png"
  enable: false
